[tool.poetry]
name = "please"
version = "0.1.0"
description = ""
authors = ["Zeffo <25067102+NayamAmarshe@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.4.1"
rich = "^12.3.0"
pyfiglet = "^0.8.post1"
python-jsonstore = "^1.3.0"
art = "^5.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
